"""Declarative command groups for the DocKube action panels.

Each category maps to a list of ``(group_title, items)`` pairs where every
item is ``(button_label, command)``. A command containing ``{arg}`` is filled
from the group's argument entry box at run time.

Keeping these as plain data means ``devops_tools`` needs a single generic
renderer instead of hundreds of near-identical button calls.
"""


def _g(title, *items):
    """Build one group; each item is a ``(label, command)`` pair."""
    return (title, list(items))


# --------------------------------------------------------------------------
# Databases
# --------------------------------------------------------------------------

DATABASE_COMMANDS = {
    "MySQL": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=mysql"),
           ("Describe", "kubectl describe statefulset mysql"),
           ("Pod Logs", "kubectl logs -l app=mysql --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=mysql")),
        _g("Client Access",
           ("Port-Forward 3306", "kubectl port-forward svc/mysql 3306:3306"),
           ("Exec: List Databases", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SHOW DATABASES;'"),
           ("Exec: List Users", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SELECT user,host FROM mysql.user;'"),
           ("Exec: Show Variables", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SHOW VARIABLES;'"),
           ("Exec: Check Version", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SELECT VERSION();'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset mysql --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset mysql --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset mysql"),
           ("Rollout History", "kubectl rollout history statefulset mysql")),
        _g("Backup",
           ("Dump to File", "kubectl exec mysql-0 -- mysqldump -u root -p appdb > backup.sql"),
           ("Copy Backup In", "kubectl cp ./backup.sql mysql-0:/tmp/backup.sql"),
           ("List PVCs", "kubectl get pvc -l app=mysql")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset mysql"),
           ("Delete Secret", "kubectl delete secret mysql-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=mysql")),
    ],
    "Postgres": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=postgres"),
           ("Describe", "kubectl describe statefulset postgres"),
           ("Pod Logs", "kubectl logs -l app=postgres --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=postgres")),
        _g("Client Access",
           ("Port-Forward 5432", "kubectl port-forward svc/postgres 5432:5432"),
           ("Exec: List Databases", "kubectl exec -it postgres-0 -- psql -U postgres -c '\\l'"),
           ("Exec: List Tables", "kubectl exec -it postgres-0 -- psql -U postgres -d appdb -c '\\dt'"),
           ("Exec: Show Version", "kubectl exec -it postgres-0 -- psql -U postgres -c 'SELECT version();'"),
           ("Exec: Activity", "kubectl exec -it postgres-0 -- psql -U postgres -c 'SELECT * FROM pg_stat_activity;'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset postgres --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset postgres --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset postgres"),
           ("Rollout History", "kubectl rollout history statefulset postgres")),
        _g("Backup",
           ("Dump to File", "kubectl exec postgres-0 -- pg_dump -U postgres appdb > backup.sql"),
           ("Dump All Databases", "kubectl exec postgres-0 -- pg_dumpall -U postgres > backup-all.sql"),
           ("Copy Backup In", "kubectl cp ./backup.sql postgres-0:/tmp/backup.sql"),
           ("List PVCs", "kubectl get pvc -l app=postgres")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset postgres"),
           ("Delete Secret", "kubectl delete secret postgres-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=postgres")),
    ],
"MongoDB": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=mongodb"),
           ("Describe", "kubectl describe statefulset mongodb"),
           ("Pod Logs", "kubectl logs -l app=mongodb --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=mongodb")),
        _g("Client Access",
           ("Port-Forward 27017", "kubectl port-forward svc/mongodb 27017:27017"),
           ("Exec: List Databases", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.adminCommand({listDatabases:1}).databases.forEach(d=>print(d.name))'"),
           ("Exec: Show Collections", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.getCollectionNames().forEach(c=>print(c))'"),
           ("Exec: Replica Status", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'rs.status()'"),
           ("Exec: Server Status", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.serverStatus()'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset mongodb --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset mongodb --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset mongodb"),
           ("Rollout History", "kubectl rollout history statefulset mongodb")),
        _g("Backup",
           ("Dump to File", "kubectl exec mongodb-0 -- mongodump --archive --gzip > backup.archive.gz"),
           ("Copy Backup In", "kubectl cp ./backup.archive.gz mongodb-0:/tmp/backup.archive.gz"),
           ("List PVCs", "kubectl get pvc -l app=mongodb")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset mongodb"),
           ("Delete Secret", "kubectl delete secret mongodb-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=mongodb")),
    ],
}

# --------------------------------------------------------------------------
# Git and GitHub
# --------------------------------------------------------------------------

GIT_GROUPS = [
    _g("Setup",
       ("Init Repository", "git init"),
       ("Clone (HTTPS)", "git clone {arg}"),
       ("Clone (SSH)", "git clone git@github.com:{arg}.git"),
       ("Show Remotes", "git remote -v"),
       ("Add Remote origin", "git remote add origin {arg}"),
       ("Set Remote URL", "git remote set-url origin {arg}"),
       ("Remove Remote", "git remote remove origin"),
       ("Prune Stale Remotes", "git remote prune origin"),
       ("Config List", "git config --list --show-origin"),
       ("Set User Name", "git config --global user.name \"{arg}\""),
       ("Set User Email", "git config --global user.email \"{arg}\"")),
    _g("Everyday Work",
       ("Status", "git status"),
       ("Status Short", "git status -sb"),
       ("Stage All", "git add ."),
       ("Stage Patch (interactive)", "git add -p"),
       ("Stage File", "git add {arg}"),
       ("Commit", "git commit -m \"{arg}\""),
       ("Commit All Tracked", "git commit -am \"{arg}\""),
       ("Amend Last Commit", "git commit --amend --no-edit"),
       ("Diff Unstaged", "git diff"),
       ("Diff Staged", "git diff --staged"),
       ("Restore File", "git restore {arg}"),
       ("Unstage File", "git restore --staged {arg}"),
       ("Move File", "git mv {arg}"),
       ("Remove File", "git rm {arg}"),
       ("Pull with Rebase", "git pull --rebase"),
       ("Push and Set Upstream", "git push -u origin {arg}")),
    _g("Branching",
       ("List Branches", "git branch"),
       ("List All Branches", "git branch -a"),
       ("Create and Switch", "git switch -c {arg}"),
       ("Switch Branch", "git switch {arg}"),
       ("Create from Current", "git checkout -b {arg}"),
       ("Merge Branch", "git merge {arg}"),
       ("Rebase onto", "git rebase {arg}"),
       ("Rebase Continue", "git rebase --continue"),
       ("Rebase Abort", "git rebase --abort"),
       ("Delete Branch", "git branch -d {arg}"),
       ("Force Delete Branch", "git branch -D {arg}")),
    _g("History and Inspection",
       ("Log", "git log"),
       ("Log Graph", "git log --oneline --graph --decorate --all"),
       ("Log Patch", "git log -p {arg}"),
       ("Show Commit", "git show {arg}"),
       ("Blame File", "git blame {arg}"),
       ("Shortlog", "git shortlog -s"),
       ("Reflog", "git reflog"),
       ("Describe Tags", "git describe --tags"),
       ("List Tags", "git tag"),
       ("Annotated Tag", "git tag -a v1.0 -m \"{arg}\""),
       ("Push Tags", "git push --tags")),
    _g("Undo and Recovery",
       ("Unstage Everything", "git restore --staged ."),
       ("Reset Soft", "git reset --soft HEAD~1"),
       ("Reset Mixed", "git reset --mixed HEAD~1"),
       ("Reset Hard (DANGER)", "git reset --hard HEAD~1"),
       ("Revert Commit", "git revert {arg}"),
       ("Cherry Pick", "git cherry-pick {arg}"),
       ("Stash", "git stash"),
       ("Stash with Message", "git stash push -m \"{arg}\""),
       ("Stash List", "git stash list"),
       ("Stash Pop", "git stash pop"),
       ("Stash Drop", "git stash drop"),
       ("Clean Preview", "git clean -n"),
       ("Clean Files (DANGER)", "git clean -fd")),
    _g("Advanced",
       ("Bisect Start", "git bisect start"),
       ("Bisect Bad", "git bisect bad"),
       ("Bisect Good", "git bisect good {arg}"),
       ("Bisect Reset", "git bisect reset"),
       ("Add Worktree", "git worktree add {arg}"),
       ("List Worktrees", "git worktree list"),
       ("Garbage Collect", "git gc --prune=now"),
       ("Check Integrity", "git fsck"),
       ("Compare Branches", "git cherry -v main"),
       ("Log Merge Commits", "git log --merges --oneline")),
]

GITHUB_CLI_GROUPS = [
    _g("Authentication",
       ("Login", "gh auth login"),
       ("Status", "gh auth status"),
       ("Logout", "gh auth logout"),
       ("Refresh Token Scopes", "gh auth refresh -s repo,workflow")),
    _g("Repositories",
       ("View Current", "gh repo view"),
       ("Clone", "gh repo clone {arg}"),
       ("Create (Private, Push)", "gh repo create {arg} --private --push"),
       ("List Mine", "gh repo list"),
       ("Open in Browser", "gh browse")),
    _g("Pull Requests",
       ("Create (from branch)", "gh pr create --fill"),
       ("List Open", "gh pr list"),
       ("List All", "gh pr list --state all"),
       ("View", "gh pr view {arg}"),
       ("Diff", "gh pr diff {arg}"),
       ("Checkout", "gh pr checkout {arg}"),
       ("Merge (Squash)", "gh pr merge {arg} --squash"),
       ("Merge (Rebase + Delete)", "gh pr merge {arg} --rebase --delete-branch")),
    _g("Issues",
       ("List Open", "gh issue list"),
       ("Create", "gh issue create --title \"{arg}\""),
       ("View", "gh issue view {arg}"),
       ("Close", "gh issue close {arg}")),
    _g("Actions and Releases",
       ("Workflow List", "gh workflow list"),
       ("Run Workflow", "gh workflow run {arg}"),
       ("Run List", "gh run list --limit 10"),
       ("Run View", "gh run view {arg}"),
       ("Re-run Failed", "gh run rerun {arg} --failed"),
       ("Cancel Run", "gh run cancel {arg}"),
       ("Create Release", "gh release create v1.0 --generate-notes"),
       ("Secrets List", "gh secret list")),
]

# --------------------------------------------------------------------------
# CI/CD
# --------------------------------------------------------------------------

CICD_GROUPS = [
    _g("GitHub Actions",
       ("List Workflows", "gh workflow list"),
       ("Run Workflow", "gh workflow run {arg}"),
       ("Recent Runs", "gh run list --limit 15"),
       ("View Run Logs", "gh run view {arg} --log-failed"),
       ("Re-run Failed", "gh run rerun {arg} --failed"),
       ("Cancel Run", "gh run cancel {arg}"),
       ("List Secrets", "gh secret list"),
       ("Set Secret", "gh secret set {arg}")),
    _g("Local Runner (act)",
       ("List Jobs", "act -l"),
       ("Run All Jobs", "act"),
       ("Run One Job", "act -j {arg}"),
       ("Run on Re-run Event", "act -r"),
       ("List Available Images", "act -l -P ubuntu-latest=catthehacker/ubuntu:act-latest")),
    _g("Build and Publish",
       ("Docker Build", "docker build -t {arg} ."),
       ("Docker Build (no cache)", "docker build --no-cache -t {arg} ."),
       ("Docker Push", "docker push {arg}"),
       ("List Images", "docker images"),
       ("Compose Up", "docker compose up -d"),
       ("Compose Down", "docker compose down")),
    _g("Deploy to Cluster",
       ("Apply Manifests", "kubectl apply -f {arg}"),
       ("Rollout Status", "kubectl rollout status deployment/{arg} --timeout=120s"),
       ("Rollout Restart", "kubectl rollout restart deployment/{arg}"),
       ("Rollout Undo", "kubectl rollout undo deployment/{arg}"),
       ("Rollout History", "kubectl rollout history deployment/{arg}"),
       ("Deployment Status", "kubectl get deployments -o wide"),
       ("Pod Logs", "kubectl logs -f deployment/{arg} --tail=100")),
]

# --------------------------------------------------------------------------
# Jenkins
# --------------------------------------------------------------------------

JENKINS_GROUPS = [
    _g("Container Lifecycle",
       ("Start Jenkins", "docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17"),
       ("Container Status", "docker ps --filter name=jenkins"),
       ("Follow Logs", "docker logs -f jenkins"),
       ("Last 200 Log Lines", "docker logs --tail 200 jenkins"),
       ("Restart", "docker restart jenkins"),
       ("Stop", "docker stop jenkins"),
       ("Remove Container", "docker rm jenkins"),
       ("Remove Volume (DELETES JOBS)", "docker volume rm jenkins_home")),
    _g("Access and Setup",
       ("Initial Admin Password", "docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword"),
       ("Shell into Container", "docker exec -it jenkins bash"),
       ("Jenkins Version", "docker exec jenkins java -jar /usr/share/jenkins/jenkins.war --version"),
       ("API Info (JSON)", "curl -s http://localhost:8080/api/json"),
       ("Computer List", "curl -s http://localhost:8080/computer/api/json?tree=computer[displayName,offline]")),
    _g("Image Management",
       ("Pull Latest LTS", "docker pull jenkins/jenkins:lts-jdk17"),
       ("List Jenkins Images", "docker images jenkins"),
       ("Remove Old Image", "docker image prune -f"),
       ("Inspect Container", "docker inspect jenkins")),
]

# --------------------------------------------------------------------------
# Terraform
# --------------------------------------------------------------------------

TERRAFORM_GROUPS = [
    _g("Core Workflow",
       ("Init", "terraform init"),
       ("Init (Upgrade)", "terraform init -upgrade"),
       ("Validate", "terraform validate"),
       ("Plan", "terraform plan"),
       ("Plan to File", "terraform plan -out=tfplan"),
       ("Apply Saved Plan", "terraform apply tfplan"),
       ("Apply (Auto Approve)", "terraform apply -auto-approve"),
       ("Apply (Full Review)", "terraform apply"),
       ("Destroy (Review First)", "terraform destroy"),
       ("Destroy (Auto Approve)", "terraform destroy -auto-approve")),
    _g("Formatting and Inspection",
       ("Format", "terraform fmt"),
       ("Format Recursive", "terraform fmt -recursive"),
       ("Format Check", "terraform fmt -check"),
       ("Show Plan File", "terraform show"),
       ("Show JSON Plan", "terraform show -json tfplan"),
       ("Providers", "terraform providers"),
       ("Version", "terraform version"),
       ("Graph", "terraform graph -type=plan")),
    _g("State Management",
       ("State List", "terraform state list"),
       ("State Show", "terraform state show {arg}"),
       ("State Remove", "terraform state rm {arg}"),
       ("Refresh State", "terraform refresh"),
       ("Force Unlock", "terraform force-unlock {arg}"),
       ("Output", "terraform output"),
       ("Output JSON", "terraform output -json"),
       ("Back Up State", "terraform state pull > terraform.tfstate.backup")),
    _g("Workspaces",
       ("List Workspaces", "terraform workspace list"),
       ("New Workspace", "terraform workspace new {arg}"),
       ("Select Workspace", "terraform workspace select {arg}"),
       ("Delete Workspace", "terraform workspace delete {arg}")),
    _g("Advanced",
       ("Import Resource", "terraform import {arg}"),
       ("Target Resource", "terraform apply -target={arg}"),
       ("Taint Resource", "terraform taint {arg}"),
       ("Untaint Resource", "terraform untaint {arg}"),
       ("Console Expression", "terraform console"),
       ("List Functions", "terraform metadata functions -json")),
]

# --------------------------------------------------------------------------
# Ansible
# --------------------------------------------------------------------------

ANSIBLE_GROUPS = [
    _g("Quick Checks",
       ("Ping All", "ansible all -m ping"),
       ("Ping Group", "ansible webservers -m ping"),
       ("Version", "ansible --version"),
       ("Ad-hoc Shell", "ansible all -m shell -a \"{arg}\""),
       ("Ad-hoc Command", "ansible all -m command -a \"{arg}\""),
       ("Run as Root", "ansible all -b -m {arg}")),
    _g("Playbooks",
       ("Run Playbook", "ansible-playbook {arg}"),
       ("Check Mode", "ansible-playbook {arg} --check --diff"),
       ("Syntax Check", "ansible-playbook {arg} --syntax-check"),
       ("Limit Hosts", "ansible-playbook {arg} --limit webservers"),
       ("Start at Task", "ansible-playbook {arg} --start-at-task \"{arg}\""),
       ("Run by Tag", "ansible-playbook {arg} --tags deploy"),
       ("List Tags", "ansible-playbook {arg} --list-tags"),
       ("Step by Step", "ansible-playbook {arg} --step"),
       ("Verbose", "ansible-playbook {arg} -vvv")),
    _g("Inventory",
       ("Inventory Graph", "ansible-inventory --graph"),
       ("Inventory List", "ansible-inventory --list"),
       ("Host Details", "ansible-inventory --host web1"),
       ("Custom Inventory File", "ansible -i {arg} all -m ping"),
       ("Gather Facts", "ansible all -m setup"),
       ("Config Dump", "ansible-config dump"),
       ("Config List", "ansible-config list")),
    _g("Vault and Collections",
       ("Create Vault", "ansible-vault create {arg}"),
       ("Edit Vault", "ansible-vault edit {arg}"),
       ("View Vault", "ansible-vault view {arg}"),
       ("Encrypt File", "ansible-vault encrypt {arg}"),
       ("Decrypt File", "ansible-vault decrypt {arg}"),
       ("Install Collection", "ansible-galaxy collection install {arg}"),
       ("List Collections", "ansible-galaxy collection list"),
       ("Init Role", "ansible-galaxy role init {arg}"),
       ("Docs List", "ansible-doc -l")),
]

# Argument placeholders shown for each group type.
ARG_PLACEHOLDERS = {
    "git": "branch, file, commit, URL...",
    "gh": "PR/issue number, repo, workflow...",
    "cicd": "workflow, job, image tag, path...",
    "terraform": "resource address, workspace...",
    "ansible": "playbook.yml, group, module...",
}