"""Ready-to-apply starter files written into the DocKube working directory.

Each entry is ``(relative_path, content)``. Paths may include a subfolder so
that ``.github/workflows/ci-cd.yml`` lands in the correct location.
These are intentionally minimal but valid so they apply without edits.
"""

import os

MYSQL_MANIFEST = """# MySQL 8 single-replica StatefulSet with a persistent volume.
# Generated by DocKube - edit freely, then use Apply Selected YAML.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: appdb
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1"]
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
"""

POSTGRES_MANIFEST = """# PostgreSQL 16 single-replica StatefulSet with a persistent volume.
# Generated by DocKube - edit freely, then use Apply Selected YAML.
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres-password: "postgres"
  postgres-db: appdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 20
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
"""

MONGODB_MANIFEST = """# MongoDB 7 single-node replica set with a persistent volume.
# Generated by DocKube - edit freely, then use Apply Selected YAML.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-root-password: "rootpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 25
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
"""

GITHUB_WORKFLOW = """# GitHub Actions CI/CD pipeline.
# Generated by DocKube - place at .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: myapp
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: python -m compileall -q .
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$TAG .
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:$TAG
      - uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Configure kubectl
        uses: azure/setup-kubectl@v4
      - name: Deploy manifests
        run: kubectl apply -f k8s/
      - name: Verify rollout
        run: kubectl rollout status deployment/myapp --timeout=120s
"""

JENKINSFILE = """// Declarative Jenkins pipeline.
// Generated by DocKube - place at the root of your repository.
pipeline {
    agent any

    environment {
        IMAGE_NAME = 'myapp'
        BUILD_TAG  = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_TAG} .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run --rm ${IMAGE_NAME}:${BUILD_TAG} python -m pytest -q'
            }
        }
        stage('Deploy') {
            when { branch 'main' }
            steps {
                sh 'docker push ${IMAGE_NAME}:${BUILD_TAG}'
            }
        }
    }

    post {
        always {
            echo 'Build finished'
        }
        failure {
            echo 'Build failed - check the console output'
        }
    }
}
"""

TERRAFORM_MAIN = """# Terraform starter configuration.
# Generated by DocKube - place at main.tf then run: terraform init
terraform {
  required_version = ">= 1.5.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

# A local file stands in for real infrastructure so the plan applies anywhere.
resource "local_file" "demo" {
  filename = "${path.module}/demo.txt"
  content  = "Created by Terraform at ${formatdate("YYYY-MM-DD", timestamp())}\\n"
}

resource "local_sensitive_file" "secret" {
  filename   = "${path.module}/secret.txt"
  content    = var.api_token
  depends_on = [local_file.demo]
}

variable "api_token" {
  description = "Example sensitive input; wire this to a real secret source."
  type        = string
  sensitive   = true
  default     = "replace-me"
}

output "demo_file" {
  value = local_file.demo.filename
}
"""

ANSIBLE_PLAYBOOK = """# Ansible playbook that configures a sample web server.
# Generated by DocKube - run with: ansible-playbook playbook.yml --check
- name: Configure sample web servers
  hosts: webservers
  become: true
  vars:
    http_port: 80

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      tags: [always]

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Restart nginx
      tags: [install]

    - name: Ensure nginx is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      tags: [service]

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
"""

ANSIBLE_INVENTORY = """# Ansible inventory.
# Generated by DocKube - run with: ansible -i inventory.ini all -m ping
[webservers]
web1 ansible_host=192.168.1.10 ansible_user=ubuntu
web2 ansible_host=192.168.1.11 ansible_user=ubuntu

[databases]
db1 ansible_host=192.168.1.20 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
"""

MANIFEST_TEMPLATES = {
    "MySQL": ("mysql.yaml", MYSQL_MANIFEST),
    "Postgres": ("postgres.yaml", POSTGRES_MANIFEST),
    "MongoDB": ("mongodb.yaml", MONGODB_MANIFEST),
}

# Templates that are written but are not YAML manifests.
AUX_TEMPLATES = {
    "GitHub Actions Workflow": (os.path.join(".github", "workflows", "ci-cd.yml"), GITHUB_WORKFLOW),
    "Jenkinsfile": ("Jenkinsfile", JENKINSFILE),
    "Terraform main.tf": ("main.tf", TERRAFORM_MAIN),
    "Ansible Playbook": ("playbook.yml", ANSIBLE_PLAYBOOK),
    "Ansible Inventory": ("inventory.ini", ANSIBLE_INVENTORY),
}