"""Declarative command groups for the DocKube action panels.

Each category maps to a list of ``(group_title, items)`` pairs where every
item is ``(button_label, command)``. A command containing ``{arg}`` is filled
from the group's argument entry box at run time.

Keeping these as plain data means ``devops_tools`` needs a single generic
renderer instead of hundreds of near-identical button calls.
"""


def _g(title, *items):
    """Build one group; each item is a ``(label, command)`` pair."""
    return (title, list(items))


# --------------------------------------------------------------------------
# Docker - the complete CLI, grouped the way it is actually used
# --------------------------------------------------------------------------

DOCKER_GROUPS = [
    _g("Info and Context",
       ("Docker Version", "docker version"),
       ("Daemon Info", "docker info"),
       ("Disk Usage", "docker system df"),
       ("Detailed Disk Usage", "docker system df -v"),
       ("List Contexts", "docker context ls"),
       ("Switch Context", "docker context use {arg}"),
       ("Daemon Events (10m)", "docker system events --since 10m")),
    _g("Run Containers",
       ("Run Nginx Detached", "docker run -d --name web -p 8080:80 nginx:alpine"),
       ("Run Interactive Shell", "docker run -it --rm ubuntu bash"),
       ("Run with Env File", "docker run -d --env-file .env --name app nginx:alpine"),
       ("Run with Named Volume", "docker run -d -v dbdata:/var/lib/postgresql/data --name db postgres:16"),
       ("Run with Bind Mount", "docker run -d -v C:/data:/data --name files nginx:alpine"),
       ("Run with Limits", "docker run -d --memory 512m --cpus 1.5 --name limited nginx:alpine"),
       ("Run with Restart Policy", "docker run -d --restart unless-stopped --name always-on nginx:alpine"),
       ("Run Read-Only", "docker run -d --read-only --tmpfs /tmp --name ro nginx:alpine"),
       ("Run as Non-Root", "docker run --user 1000:1000 --rm ubuntu id"),
       ("Run Localhost Only", "docker run -d -p 127.0.0.1:5432:5432 --name db postgres:16"),
       ("Run on Custom Network", "docker run -d --network app-net --name api nginx:alpine"),
       ("Run with Healthcheck", "docker run -d --health-cmd \"curl -f http://localhost/ || exit 1\" --health-interval 30s --name hc nginx:alpine")),
    _g("Container Lifecycle",
       ("Start", "docker start {arg}"),
       ("Stop", "docker stop {arg}"),
       ("Restart", "docker restart {arg}"),
       ("Kill (SIGKILL)", "docker kill {arg}"),
       ("Pause", "docker pause {arg}"),
       ("Unpause", "docker unpause {arg}"),
       ("Remove", "docker rm {arg}"),
       ("Force Remove", "docker rm -f {arg}"),
       ("Rename", "docker rename {arg} renamed"),
       ("Create Only", "docker create --name created nginx:alpine"),
       ("Wait for Exit", "docker wait {arg}"),
       ("Update Memory Limit", "docker update --memory 1g {arg}")),
    _g("Inspect and Logs",
       ("List Running", "docker ps"),
       ("List All", "docker ps -a"),
       ("List IDs Only", "docker ps -q"),
       ("List Exited", "docker ps -a --filter status=exited --format \"table {{.Names}}\\t{{.Status}}\""),
       ("Follow Logs", "docker logs -f {arg}"),
       ("Last 100 Log Lines", "docker logs --tail 100 {arg}"),
       ("Logs Since 10m", "docker logs --since 10m {arg}"),
       ("Inspect", "docker inspect {arg}"),
       ("Container IP", "docker inspect -f \"{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}\" {arg}"),
       ("Exit Code", "docker inspect -f \"{{.State.ExitCode}}\" {arg}"),
       ("Health Status", "docker inspect -f \"{{json .State.Health}}\" {arg}"),
       ("Live Stats", "docker stats"),
       ("Stats Snapshot", "docker stats --no-stream"),
       ("Process List", "docker top {arg}"),
       ("Filesystem Changes", "docker diff {arg}"),
       ("Port Mappings", "docker port {arg}")),
    _g("Exec and Copy",
       ("Shell (sh)", "docker exec -it {arg} sh"),
       ("Shell (bash)", "docker exec -it {arg} bash"),
       ("Shell as Root", "docker exec -u root -it {arg} sh"),
       ("Run Command Inside", "docker exec {arg} printenv"),
       ("Copy File Out", "docker cp {arg}:/var/log/app.log ./app.log"),
       ("Copy File In", "docker cp ./config.yml {arg}:/etc/app/config.yml"),
       ("Export Filesystem", "docker export {arg} -o container-snapshot.tar")),
    _g("Images",
       ("Pull Image", "docker pull {arg}"),
       ("List Images", "docker images"),
       ("List With Dangling", "docker images -a"),
       ("Tag Image", "docker tag {arg} myrepo/app:1.0"),
       ("Push Image", "docker push {arg}"),
       ("Remove Image", "docker rmi {arg}"),
       ("Image History", "docker history {arg}"),
       ("Image Inspect", "docker image inspect {arg}"),
       ("Save to Tar", "docker image save {arg} -o image.tar"),
       ("Load from Tar", "docker image load -i image.tar"),
       ("Search Hub", "docker search {arg}"),
       ("Prune Dangling", "docker image prune -f")),
    _g("Build and BuildKit",
       ("Build Image", "docker build -t {arg} ."),
       ("Build (no cache)", "docker build --no-cache -t app:dev ."),
       ("Build (fresh base)", "docker build --pull -t app:dev ."),
       ("Build Prod Dockerfile", "docker build -f Dockerfile.prod -t app:prod ."),
       ("Build Specific Target", "docker build --target test -t app:test ."),
       ("Build with Build Arg", "docker build --build-arg VERSION=1.0 -t app:1.0 ."),
       ("Buildx Multi-Arch (push)", "docker buildx build --platform linux/amd64,linux/arm64 -t {arg} --push ."),
       ("List Buildx Builders", "docker buildx ls"),
       ("Prune Build Cache", "docker builder prune -a -f"),
       ("Clean After Build", "docker build -t app:dev . && docker image prune -f")),
    _g("Networks",
       ("List Networks", "docker network ls"),
       ("Create Network", "docker network create {arg}"),
       ("Create with Subnet", "docker network create --subnet 10.10.0.0/24 app-net"),
       ("Inspect Network", "docker network inspect {arg}"),
       ("Connect Container", "docker network connect {arg} mycontainer"),
       ("Disconnect Container", "docker network disconnect {arg} mycontainer"),
       ("Remove Network", "docker network rm {arg}"),
       ("Prune Networks", "docker network prune -f")),
    _g("Volumes",
       ("List Volumes", "docker volume ls"),
       ("Create Volume", "docker volume create {arg}"),
       ("Inspect Volume", "docker volume inspect {arg}"),
       ("Remove Volume", "docker volume rm {arg}"),
       ("Prune Volumes (DELETES DATA)", "docker volume prune -f"),
       ("Backup Volume", "docker run --rm -v dbdata:/data -v C:/backup:/backup alpine tar czf /backup/vol.tar.gz -C /data ."),
       ("Find Volume Path", "docker volume inspect dbdata --format \"{{.Mountpoint}}\"")),
    _g("Docker Compose",
       ("Up Detached", "docker compose up -d"),
       ("Up Rebuild", "docker compose up -d --build"),
       ("Compose Status", "docker compose ps"),
       ("Compose Logs", "docker compose logs -f --tail 100"),
       ("Compose Logs (service)", "docker compose logs -f web"),
       ("Exec in Service", "docker compose exec db psql -U app"),
       ("One-Off Task", "docker compose run --rm web pytest"),
       ("Restart Service", "docker compose restart web"),
       ("Stop Services", "docker compose stop"),
       ("Start Services", "docker compose start"),
       ("Pull Images", "docker compose pull"),
       ("Build Services", "docker compose build --no-cache"),
       ("Validate Config", "docker compose config"),
       ("Down (keep data)", "docker compose down"),
       ("Down + Delete Data", "docker compose down -v"),
       ("Down Everything", "docker compose down --rmi all --volumes"),
       ("Compose File", "docker compose -f {arg} up -d")),
    _g("Registry and Auth",
       ("Login Docker Hub", "docker login"),
       ("Login (stdin)", "docker login registry.example.com -u ci --password-stdin"),
       ("Logout", "docker logout"),
       ("Push to Registry", "docker push {arg}"),
       ("Pull from Registry", "docker pull {arg}"),
       ("Retag for Registry", "docker tag app:1.0 registry.example.com/app:1.0"),
       ("Inspect Manifest", "docker manifest inspect {arg}")),
    _g("Swarm and Services",
       ("Init Swarm", "docker swarm init"),
       ("Worker Join Token", "docker swarm join-token worker"),
       ("List Nodes", "docker node ls"),
       ("Create Service", "docker service create --name {arg} --replicas 3 nginx:alpine"),
       ("List Services", "docker service ls"),
       ("Service Tasks", "docker service ps {arg}"),
       ("Scale Service", "docker service scale web=3"),
       ("Update Service Image", "docker service update --image nginx:alpine web"),
       ("Service Logs", "docker service logs web"),
       ("Deploy Stack", "docker stack deploy -c docker-compose.yml {arg}"),
       ("List Stacks", "docker stack ls"),
       ("Remove Stack", "docker stack rm {arg}")),
    _g("System Cleanup (read system df first)",
       ("Prune Containers", "docker container prune -f"),
       ("Prune Images", "docker image prune -f"),
       ("Prune All Images", "docker image prune -a -f"),
       ("Prune Networks", "docker network prune -f"),
       ("Prune Build Cache", "docker builder prune -a -f"),
       ("System Prune", "docker system prune"),
       ("System Prune + Volumes (DELETES DATA)", "docker system prune -a --volumes")),
    _g("Debug and Troubleshooting",
       ("Events for Container", "docker system events --filter container={arg} --since 10m"),
       ("Live Resource Stats", "docker stats --no-stream --format \"table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}\""),
       ("All Container IPs", "docker ps -q | xargs docker inspect -f \"{{.Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}\""),
       ("Find Who Uses Space", "docker system df -v"),
       ("Image Layers", "docker history {arg}"),
       ("Configured Entrypoint", "docker inspect -f \"{{json .Config.Entrypoint}}\" {arg}"),
       ("Restart Count", "docker inspect -f \"{{.RestartCount}}\" {arg}"),
       ("Failed Health Logs", "docker inspect -f \"{{json .State.Health.Log}}\" {arg}")),
]

# --------------------------------------------------------------------------
# Databases
# ----------------------------------------------------------------

DATABASE_COMMANDS = {
    "MySQL": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=mysql"),
           ("Describe", "kubectl describe statefulset mysql"),
           ("Pod Logs", "kubectl logs -l app=mysql --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=mysql")),
        _g("Client Access",
           ("Port-Forward 3306", "kubectl port-forward svc/mysql 3306:3306"),
           ("Exec: List Databases", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SHOW DATABASES;'"),
           ("Exec: List Users", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SELECT user,host FROM mysql.user;'"),
           ("Exec: Show Variables", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SHOW VARIABLES;'"),
           ("Exec: Check Version", "kubectl exec -it mysql-0 -- mysql -u root -p -e 'SELECT VERSION();'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset mysql --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset mysql --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset mysql"),
           ("Rollout History", "kubectl rollout history statefulset mysql")),
        _g("Backup",
           ("Dump to File", "kubectl exec mysql-0 -- mysqldump -u root -p appdb > backup.sql"),
           ("Copy Backup In", "kubectl cp ./backup.sql mysql-0:/tmp/backup.sql"),
           ("List PVCs", "kubectl get pvc -l app=mysql")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset mysql"),
           ("Delete Secret", "kubectl delete secret mysql-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=mysql")),
        _g("SQL Commands - Databases",
           ("Show Databases", "mysql -u root -p -e 'SHOW DATABASES;'"),
           ("Create Database", "mysql -u root -p -e 'CREATE DATABASE {arg};'"),
           ("Drop Database", "mysql -u root -p -e 'DROP DATABASE {arg};'"),
           ("Use Database", "mysql -u root -p -D {arg} -e 'SELECT DATABASE();'"),
           ("Show Create Database", "mysql -u root -p -e 'SHOW CREATE DATABASE {arg};'")),
        _g("SQL Commands - Tables",
           ("Show Tables", "mysql -u root -p -D {arg} -e 'SHOW TABLES;'"),
           ("Create Table", "mysql -u root -p -D {arg} -e 'CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), email VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);'"),
           ("Describe Table", "mysql -u root -p -D {arg} -e 'DESCRIBE users;'"),
           ("Show Create Table", "mysql -u root -p -D {arg} -e 'SHOW CREATE TABLE users\\G'"),
           ("Alter Table Add Column", "mysql -u root -p -D {arg} -e 'ALTER TABLE users ADD COLUMN phone VARCHAR(20);'"),
           ("Alter Table Drop Column", "mysql -u root -p -D {arg} -e 'ALTER TABLE users DROP COLUMN phone;'"),
           ("Rename Table", "mysql -u root -p -D {arg} -e 'RENAME TABLE users TO customers;'"),
           ("Truncate Table", "mysql -u root -p -D {arg} -e 'TRUNCATE TABLE users;'"),
           ("Drop Table", "mysql -u root -p -D {arg} -e 'DROP TABLE users;'")),
        _g("SQL Commands - Data Manipulation",
           ("Insert Row", "mysql -u root -p -D {arg} -e \"INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');\""),
           ("Insert Multiple", "mysql -u root -p -D {arg} -e \"INSERT INTO users (name, email) VALUES ('Jane', 'jane@test.com'), ('Bob', 'bob@test.com');\""),
           ("Select All", "mysql -u root -p -D {arg} -e 'SELECT * FROM users;'"),
           ("Select With Where", "mysql -u root -p -D {arg} -e \"SELECT * FROM users WHERE email='john@example.com';\""),
           ("Update Row", "mysql -u root -p -D {arg} -e \"UPDATE users SET name='John Smith' WHERE email='john@example.com';\""),
           ("Delete Row", "mysql -u root -p -D {arg} -e \"DELETE FROM users WHERE email='john@example.com';\""),
           ("Limit Results", "mysql -u root -p -D {arg} -e 'SELECT * FROM users LIMIT 10;'"),
           ("Order By", "mysql -u root -p -D {arg} -e 'SELECT * FROM users ORDER BY created_at DESC;'")),
        _g("SQL Commands - Indexes & Keys",
           ("Show Indexes", "mysql -u root -p -D {arg} -e 'SHOW INDEX FROM users;'"),
           ("Create Index", "mysql -u root -p -D {arg} -e 'CREATE INDEX idx_email ON users(email);'"),
           ("Create Unique Index", "mysql -u root -p -D {arg} -e 'CREATE UNIQUE INDEX idx_email_unique ON users(email);'"),
           ("Drop Index", "mysql -u root -p -D {arg} -e 'DROP INDEX idx_email ON users;'"),
           ("Add Primary Key", "mysql -u root -p -D {arg} -e 'ALTER TABLE users ADD PRIMARY KEY (id);'"),
           ("Add Foreign Key", "mysql -u root -p -D {arg} -e 'ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(id);'"),
           ("Show Keys", "mysql -u root -p -D {arg} -e 'SHOW KEYS FROM users;'")),
        _g("SQL Commands - Users & Permissions",
           ("List Users", "mysql -u root -p -e 'SELECT User, Host FROM mysql.user;'"),
           ("Create User", "mysql -u root -p -e \"CREATE USER 'newuser'@'%' IDENTIFIED BY 'password';\""),
           ("Grant All Privileges", "mysql -u root -p -e \"GRANT ALL PRIVILEGES ON *.* TO 'newuser'@'%' WITH GRANT OPTION;\""),
           ("Grant On Database", "mysql -u root -p -e \"GRANT ALL PRIVILEGES ON {arg}.* TO 'newuser'@'%';\""),
           ("Show Grants", "mysql -u root -p -e \"SHOW GRANTS FOR 'newuser'@'%';\""),
           ("Revoke Privileges", "mysql -u root -p -e \"REVOKE ALL PRIVILEGES ON {arg}.* FROM 'newuser'@'%';\""),
           ("Drop User", "mysql -u root -p -e \"DROP USER 'newuser'@'%';\""),
           ("Change Password", "mysql -u root -p -e \"ALTER USER 'newuser'@'%' IDENTIFIED BY 'newpassword';\""),
           ("Flush Privileges", "mysql -u root -p -e 'FLUSH PRIVILEGES;'")),
        _g("SQL Commands - Performance & Diagnostics",
           ("Show Processlist", "mysql -u root -p -e 'SHOW FULL PROCESSLIST;'"),
           ("Show Status", "mysql -u root -p -e 'SHOW GLOBAL STATUS;'"),
           ("Show Variables", "mysql -u root -p -e 'SHOW GLOBAL VARIABLES;'"),
           ("Show Engine InnoDB Status", "mysql -u root -p -e 'SHOW ENGINE INNODB STATUS\\G'"),
           ("Explain Query", "mysql -u root -p -D {arg} -e 'EXPLAIN SELECT * FROM users WHERE email=\"john@example.com\";'"),
           ("Analyze Table", "mysql -u root -p -D {arg} -e 'ANALYZE TABLE users;'"),
           ("Optimize Table", "mysql -u root -p -D {arg} -e 'OPTIMIZE TABLE users;'"),
           ("Check Table", "mysql -u root -p -D {arg} -e 'CHECK TABLE users;'"),
           ("Repair Table", "mysql -u root -p -D {arg} -e 'REPAIR TABLE users;'")),
        _g("SQL Commands - Backup & Restore (Local)",
           ("Dump Database", "mysqldump -u root -p {arg} > dump.sql"),
           ("Dump All Databases", "mysqldump -u root -p --all-databases > alldb.sql"),
           ("Dump Schema Only", "mysqldump -u root -p --no-data {arg} > schema.sql"),
           ("Dump With Compression", "mysqldump -u root -p {arg} | gzip > dump.sql.gz"),
           ("Restore Database", "mysql -u root -p {arg} < dump.sql"),
           ("Restore All Databases", "mysql -u root -p < alldb.sql")),
    "Postgres": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=postgres"),
           ("Describe", "kubectl describe statefulset postgres"),
           ("Pod Logs", "kubectl logs -l app=postgres --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=postgres")),
        _g("Client Access",
           ("Port-Forward 5432", "kubectl port-forward svc/postgres 5432:5432"),
           ("Exec: List Databases", "kubectl exec -it postgres-0 -- psql -U postgres -c '\\l'"),
           ("Exec: List Tables", "kubectl exec -it postgres-0 -- psql -U postgres -d appdb -c '\\dt'"),
           ("Exec: Show Version", "kubectl exec -it postgres-0 -- psql -U postgres -c 'SELECT version();'"),
           ("Exec: Activity", "kubectl exec -it postgres-0 -- psql -U postgres -c 'SELECT * FROM pg_stat_activity;'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset postgres --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset postgres --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset postgres"),
           ("Rollout History", "kubectl rollout history statefulset postgres")),
        _g("Backup",
           ("Dump to File", "kubectl exec postgres-0 -- pg_dump -U postgres appdb > backup.sql"),
           ("Dump All Databases", "kubectl exec postgres-0 -- pg_dumpall -U postgres > backup-all.sql"),
           ("Copy Backup In", "kubectl cp ./backup.sql postgres-0:/tmp/backup.sql"),
           ("List PVCs", "kubectl get pvc -l app=postgres")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset postgres"),
           ("Delete Secret", "kubectl delete secret postgres-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=postgres")),
        _g("SQL Commands - Databases",
           ("List Databases", "psql -U postgres -c '\\\\l'"),
           ("Create Database", "psql -U postgres -c 'CREATE DATABASE {arg};'"),
           ("Drop Database", "psql -U postgres -c 'DROP DATABASE {arg};'"),
           ("Connect to Database", "psql -U postgres -d {arg}"),
           ("Show Current Database", "psql -U postgres -d {arg} -c 'SELECT current_database();'")),
        _g("SQL Commands - Tables",
           ("List Tables", "psql -U postgres -d {arg} -c '\\\\dt'"),
           ("Describe Table", "psql -U postgres -d {arg} -c '\\\\d+ users'"),
           ("Create Table", "psql -U postgres -d {arg} -c 'CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);'"),
           ("Show Create Table", "psql -U postgres -d {arg} -c '\\\\d users'"),
           ("Alter Table Add Column", "psql -U postgres -d {arg} -c 'ALTER TABLE users ADD COLUMN phone VARCHAR(20);'"),
           ("Alter Table Drop Column", "psql -U postgres -d {arg} -c 'ALTER TABLE users DROP COLUMN phone;'"),
           ("Rename Table", "psql -U postgres -d {arg} -c 'ALTER TABLE users RENAME TO customers;'"),
           ("Truncate Table", "psql -U postgres -d {arg} -c 'TRUNCATE TABLE users;'"),
           ("Drop Table", "psql -U postgres -d {arg} -c 'DROP TABLE users;'")),
        _g("SQL Commands - Data Manipulation",
           ("Insert Row", "psql -U postgres -d {arg} -c \"INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');\""),
           ("Insert Multiple", "psql -U postgres -d {arg} -c \"INSERT INTO users (name, email) VALUES ('Jane', 'jane@test.com'), ('Bob', 'bob@test.com');\""),
           ("Select All", "psql -U postgres -d {arg} -c 'SELECT * FROM users;'"),
           ("Select With Where", "psql -U postgres -d {arg} -c \"SELECT * FROM users WHERE email='john@example.com';\""),
           ("Update Row", "psql -U postgres -d {arg} -c \"UPDATE users SET name='John Smith' WHERE email='john@example.com';\""),
           ("Delete Row", "psql -U postgres -d {arg} -c \"DELETE FROM users WHERE email='john@example.com';\""),
           ("Limit Results", "psql -U postgres -d {arg} -c 'SELECT * FROM users LIMIT 10;'"),
           ("Order By", "psql -U postgres -d {arg} -c 'SELECT * FROM users ORDER BY created_at DESC;'")),
        _g("SQL Commands - Indexes & Constraints",
           ("List Indexes", "psql -U postgres -d {arg} -c '\\\\di'"),
           ("Create Index", "psql -U postgres -d {arg} -c 'CREATE INDEX idx_email ON users(email);'"),
           ("Create Unique Index", "psql -U postgres -d {arg} -c 'CREATE UNIQUE INDEX idx_email_unique ON users(email);'"),
           ("Drop Index", "psql -U postgres -d {arg} -c 'DROP INDEX idx_email;'"),
           ("Add Primary Key", "psql -U postgres -d {arg} -c 'ALTER TABLE users ADD PRIMARY KEY (id);'"),
           ("Add Foreign Key", "psql -U postgres -d {arg} -c 'ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users(id);'"),
           ("Add Check Constraint", "psql -U postgres -d {arg} -c 'ALTER TABLE users ADD CONSTRAINT chk_email CHECK (email LIKE %@%);'")),
        _g("SQL Commands - Users & Permissions",
           ("List Users", "psql -U postgres -c '\\\\du'"),
           ("Create User", "psql -U postgres -c \"CREATE USER newuser WITH PASSWORD 'password';\""),
           ("Create Superuser", "psql -U postgres -c \"CREATE USER admin WITH SUPERUSER PASSWORD 'adminpass';\""),
           ("Grant All On Database", "psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE {arg} TO newuser;\""),
           ("Grant All On Schema", "psql -U postgres -d {arg} -c 'GRANT ALL ON SCHEMA public TO newuser;'"),
           ("Grant On All Tables", "psql -U postgres -d {arg} -c 'GRANT ALL ON ALL TABLES IN SCHEMA public TO newuser;'"),
           ("Revoke Privileges", "psql -U postgres -c \"REVOKE ALL PRIVILEGES ON DATABASE {arg} FROM newuser;\""),
           ("Drop User", "psql -U postgres -c 'DROP USER newuser;'"),
           ("Alter User Password", "psql -U postgres -c \"ALTER USER newuser WITH PASSWORD 'newpassword';\"")),
        _g("SQL Commands - Performance & Diagnostics",
           ("Show Activity", "psql -U postgres -c 'SELECT * FROM pg_stat_activity;'"),
           ("Show Table Stats", "psql -U postgres -d {arg} -c 'SELECT * FROM pg_stat_user_tables;'"),
           ("Show Index Stats", "psql -U postgres -d {arg} -c 'SELECT * FROM pg_stat_user_indexes;'"),
           ("Show Database Size", "psql -U postgres -c 'SELECT pg_size_pretty(pg_database_size({arg}));'"),
           ("Show Table Size", "psql -U postgres -d {arg} -c 'SELECT pg_size_pretty(pg_total_relation_size('users'));'"),
           ("Explain Query", "psql -U postgres -d {arg} -c 'EXPLAIN ANALYZE SELECT * FROM users WHERE email=\'john@example.com\';'"),
           ("Vacuum Analyze", "psql -U postgres -d {arg} -c 'VACUUM ANALYZE;'"),
           ("Show Locks", "psql -U postgres -c 'SELECT * FROM pg_locks WHERE NOT granted;'")),
        _g("SQL Commands - Backup & Restore (Local)",
           ("Dump Database", "pg_dump -U postgres {arg} > dump.sql"),
           ("Dump All Databases", "pg_dumpall -U postgres > alldb.sql"),
           ("Dump Schema Only", "pg_dump -U postgres -s {arg} > schema.sql"),
           ("Dump Data Only", "pg_dump -U postgres -a {arg} > data.sql"),
           ("Dump With Compression", "pg_dump -U postgres {arg} | gzip > dump.sql.gz"),
           ("Restore Database", "psql -U postgres -d {arg} < dump.sql"),
           ("Restore All Databases", "psql -U postgres < alldb.sql")),
    ],
"MongoDB": [
        _g("Workload",
           ("Get Pods", "kubectl get pods -l app=mongodb"),
           ("Describe", "kubectl describe statefulset mongodb"),
           ("Pod Logs", "kubectl logs -l app=mongodb --tail=50 -f"),
           ("All Resources", "kubectl get all -l app=mongodb")),
        _g("Client Access",
           ("Port-Forward 27017", "kubectl port-forward svc/mongodb 27017:27017"),
           ("Exec: List Databases", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.adminCommand({listDatabases:1}).databases.forEach(d=>print(d.name))'"),
           ("Exec: Show Collections", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.getCollectionNames().forEach(c=>print(c))'"),
           ("Exec: Replica Status", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'rs.status()'"),
           ("Exec: Server Status", "kubectl exec -it mongodb-0 -- mongosh --quiet --eval 'db.serverStatus()'")),
        _g("Scale and Rollout",
           ("Scale to 3", "kubectl scale statefulset mongodb --replicas=3"),
           ("Scale to 1", "kubectl scale statefulset mongodb --replicas=1"),
           ("Restart", "kubectl rollout restart statefulset mongodb"),
           ("Rollout History", "kubectl rollout history statefulset mongodb")),
        _g("Backup",
           ("Dump to File", "kubectl exec mongodb-0 -- mongodump --archive --gzip > backup.archive.gz"),
           ("Copy Backup In", "kubectl cp ./backup.archive.gz mongodb-0:/tmp/backup.archive.gz"),
           ("List PVCs", "kubectl get pvc -l app=mongodb")),
        _g("Cleanup",
           ("Delete StatefulSet", "kubectl delete statefulset mongodb"),
           ("Delete Secret", "kubectl delete secret mongodb-secret"),
           ("Delete PVCs (DESTROYS DATA)", "kubectl delete pvc -l app=mongodb")),
        _g("NoSQL Commands - Databases",
           ("Show Databases", "mongosh --eval 'db.adminCommand({listDatabases:1})'"),
           ("Create Database", "mongosh {arg} --eval 'db.createCollection(\"test\")'"),
           ("Drop Database", "mongosh {arg} --eval 'db.dropDatabase()'"),
           ("Use Database", "mongosh {arg} --eval 'db.getName()'"),
           ("Show Database Stats", "mongosh {arg} --eval 'db.stats()'")),
        _g("NoSQL Commands - Collections",
           ("List Collections", "mongosh {arg} --eval 'db.getCollectionNames()'"),
           ("Create Collection", "mongosh {arg} --eval 'db.createCollection(\"users\")'"),
           ("Create Capped Collection", "mongosh {arg} --eval 'db.createCollection(\"logs\", {capped: true, size: 1000000})'"),
           ("Show Collection Stats", "mongosh {arg} --eval 'db.users.stats()'"),
           ("Rename Collection", "mongosh {arg} --eval 'db.users.renameCollection(\"customers\")'"),
           ("Drop Collection", "mongosh {arg} --eval 'db.users.drop()'")),
        _g("NoSQL Commands - Documents (CRUD)",
           ("Insert One", "mongosh {arg} --eval 'db.users.insertOne({name: \"John Doe\", email: \"john@example.com\", createdAt: new Date()})'"),
           ("Insert Many", "mongosh {arg} --eval 'db.users.insertMany([{name: \"Jane\", email: \"jane@test.com\"}, {name: \"Bob\", email: \"bob@test.com\"}])'"),
           ("Find All", "mongosh {arg} --eval 'db.users.find()'"),
           ("Find One", "mongosh {arg} --eval 'db.users.findOne({email: \"john@example.com\"})'"),
           ("Find With Filter", "mongosh {arg} --eval 'db.users.find({status: \"active\"})'"),
           ("Find With Projection", "mongosh {arg} --eval 'db.users.find({}, {name: 1, email: 1, _id: 0})'"),
           ("Update One", "mongosh {arg} --eval 'db.users.updateOne({email: \"john@example.com\"}, {$set: {name: \"John Smith\"}})'"),
           ("Update Many", "mongosh {arg} --eval 'db.users.updateMany({status: \"inactive\"}, {$set: {status: \"archived\"}})'"),
           ("Delete One", "mongosh {arg} --eval 'db.users.deleteOne({email: \"john@example.com\"})'"),
           ("Delete Many", "mongosh {arg} --eval 'db.users.deleteMany({status: \"archived\"})'"),
           ("Replace One", "mongosh {arg} --eval 'db.users.replaceOne({email: \"john@example.com\"}, {name: \"John Updated\", email: \"john@example.com\", updatedAt: new Date()})'"),
           ("Upsert", "mongosh {arg} --eval 'db.users.updateOne({email: \"new@test.com\"}, {$set: {name: \"New User\"}}, {upsert: true})'")),

_g("NoSQL Commands - Query Operators",
           ("Find - Comparison ($gt, $lt)", "mongosh {arg} --eval 'db.users.find({age: {$gt: 25, $lt: 50}})'"),
           ("Find - In Array ($in)", "mongosh {arg} --eval 'db.users.find({status: {$in: [\"active\", \"pending\"]}})'"),
           ("Find - Regex", "mongosh {arg} --eval 'db.users.find({email: {$regex: \"@gmail.com$\"}})'"),
           ("Find - Exists", "mongosh {arg} --eval 'db.users.find({phone: {$exists: true}})'"),
           ("Find - And / Or", "mongosh {arg} --eval 'db.users.find({$or: [{status: \"active\"}, {age: {$lt: 18}}]})'"),
           ("Find - Text Search", "mongosh {arg} --eval 'db.users.find({$text: {$search: \"john\"}})'"),
           ("Sort and Limit", "mongosh {arg} --eval 'db.users.find().sort({createdAt: -1}).limit(10)'"),
           ("Count Documents", "mongosh {arg} --eval 'db.users.countDocuments({status: \"active\"})'"),
           ("Distinct Values", "mongosh {arg} --eval 'db.users.distinct(\"status\")'")),
        _g("NoSQL Commands - Aggregation Pipeline",
           ("Group By Status", "mongosh {arg} --eval 'db.users.aggregate([{$group: {_id: \"$status\", count: {$sum: 1}}}])'"),
           ("Group And Sum", "mongosh {arg} --eval 'db.orders.aggregate([{$group: {_id: \"$customerId\", total: {$sum: \"$amount\"}}}, {$sort: {total: -1}}])'"),
           ("Lookup (Join)", "mongosh {arg} --eval 'db.orders.aggregate([{$lookup: {from: \"users\", localField: \"customerId\", foreignField: \"_id\", as: \"customer\"}}])'"),
           ("Unwind Array", "mongosh {arg} --eval 'db.orders.aggregate([{$unwind: \"$items\"}])'"),
           ("Project Fields", "mongosh {arg} --eval 'db.users.aggregate([{$project: {name: 1, email: 1, domain: {$substr: [\"$email\", {$indexOfCP: [\"$email\", \"@\"]}, -1]}}]})'"),
           ("Facet (Multiple Pipelines)", "mongosh {arg} --eval 'db.users.aggregate([{$facet: {active: [{$match: {status: \"active\"}}], inactive: [{$match: {status: \"inactive\"}}]}}])'")),
# --------------------------------------------------------------------------
_g("NoSQL Commands - Indexes",
           ("List Indexes", "mongosh {arg} --eval 'db.users.getIndexes()'"),
           ("Create Single Field Index", "mongosh {arg} --eval 'db.users.createIndex({email: 1})'"),
           ("Create Compound Index", "mongosh {arg} --eval 'db.users.createIndex({lastName: 1, firstName: 1})'"),
           ("Create Unique Index", "mongosh {arg} --eval 'db.users.createIndex({email: 1}, {unique: true})'"),
           ("Create Text Index", "mongosh {arg} --eval 'db.users.createIndex({name: \"text\", email: \"text\"})'"),
           ("Create TTL Index", "mongosh {arg} --eval 'db.logs.createIndex({createdAt: 1}, {expireAfterSeconds: 86400})'"),
           ("Create Partial Index", "mongosh {arg} --eval 'db.users.createIndex({status: 1}, {partialFilterExpression: {status: \"active\"}})'"),
           ("Drop Index", "mongosh {arg} --eval 'db.users.dropIndex(\"email_1\")'"),
           ("Hide Index", "mongosh {arg} --eval 'db.users.hideIndex(\"email_1\")'"),
           ("Show Hidden Indexes", "mongosh {arg} --eval 'db.users.getIndexes().filter(i => i.hidden)'")),
        _g("NoSQL Commands - Users & Roles",
           ("List Users", "mongosh admin --eval 'db.getUsers()'"),
           ("Create User", "mongosh admin --eval 'db.createUser({user: \"appuser\", pwd: \"password\", roles: [{role: \"readWrite\", db: \"{arg}\"}]})'"),
           ("Create Admin User", "mongosh admin --eval 'db.createUser({user: \"admin\", pwd: \"adminpass\", roles: [\"userAdminAnyDatabase\", \"dbAdminAnyDatabase\", \"readWriteAnyDatabase\"]})'"),
           ("Grant Role", "mongosh admin --eval 'db.grantRolesToUser(\"appuser\", [{role: \"readWrite\", db: \"{arg}\"}])'"),
           ("Revoke Role", "mongosh admin --eval 'db.revokeRolesFromUser(\"appuser\", [{role: \"readWrite\", db: \"{arg}\"}])'"),
           ("Drop User", "mongosh admin --eval 'db.dropUser(\"appuser\")'"),
           ("Change Password", "mongosh admin --eval 'db.changeUserPassword(\"appuser\", \"newpassword\")'"),
           ("Show User Roles", "mongosh admin --eval 'db.getUser(\"appuser\")'")),
        _g("NoSQL Commands - Performance & Diagnostics",
           ("Server Status", "mongosh {arg} --eval 'db.serverStatus()'"),
           ("Replica Set Status", "mongosh {arg} --eval 'rs.status()'"),
           ("Current Ops", "mongosh {arg} --eval 'db.currentOp()'"),
           ("Explain Query", "mongosh {arg} --eval 'db.users.find({email: \"john@example.com\"}).explain(\"executionStats\")'"),
           ("Collection Stats", "mongosh {arg} --eval 'db.users.stats()'"),
           ("Index Stats", "mongosh {arg} --eval 'db.users.aggregate([{$indexStats: {}}])'"),
           ("Top Command", "mongosh {arg} --eval 'db.adminCommand({top: 1})'"),
           ("Profile Level", "mongosh {arg} --eval 'db.setProfilingLevel(1, {slowms: 100})'"),
           ("Get Profiling Info", "mongosh {arg} --eval 'db.system.profile.find().limit(5).sort({ts: -1})'")),
        _g("NoSQL Commands - Backup & Restore (Local)",
           ("Dump Database", "mongodump --db {arg} --out ./backup"),
           ("Dump All Databases", "mongodump --out ./backup"),
           ("Dump Collection", "mongodump --db {arg} --collection users --out ./backup"),
           ("Dump With Gzip", "mongodump --db {arg} --gzip --out ./backup"),
           ("Restore Database", "mongorestore --db {arg} ./backup/{arg}"),
           ("Restore All Databases", "mongorestore ./backup"),
           ("Restore Collection", "mongorestore --db {arg} --collection users ./backup/{arg}/users.bson"),
           ("Restore With Drop", "mongorestore --drop --db {arg} ./backup/{arg}")),
# Git and GitHub
# --------------------------------------------------------------------------

GIT_GROUPS = [
    _g("Setup",
       ("Init Repository", "git init"),
       ("Clone (HTTPS)", "git clone {arg}"),
       ("Clone (SSH)", "git clone git@github.com:{arg}.git"),
       ("Show Remotes", "git remote -v"),
       ("Add Remote origin", "git remote add origin {arg}"),
       ("Set Remote URL", "git remote set-url origin {arg}"),
       ("Remove Remote", "git remote remove origin"),
       ("Prune Stale Remotes", "git remote prune origin"),
       ("Config List", "git config --list --show-origin"),
       ("Set User Name", "git config --global user.name \"{arg}\""),
       ("Set User Email", "git config --global user.email \"{arg}\"")),
    _g("Everyday Work",
       ("Status", "git status"),
       ("Status Short", "git status -sb"),
       ("Stage All", "git add ."),
       ("Stage Patch (interactive)", "git add -p"),
       ("Stage File", "git add {arg}"),
       ("Commit", "git commit -m \"{arg}\""),
       ("Commit All Tracked", "git commit -am \"{arg}\""),
       ("Amend Last Commit", "git commit --amend --no-edit"),
       ("Diff Unstaged", "git diff"),
       ("Diff Staged", "git diff --staged"),
       ("Restore File", "git restore {arg}"),
       ("Unstage File", "git restore --staged {arg}"),
       ("Move File", "git mv {arg}"),
       ("Remove File", "git rm {arg}"),
       ("Pull with Rebase", "git pull --rebase"),
       ("Push and Set Upstream", "git push -u origin {arg}")),
    _g("Branching",
       ("List Branches", "git branch"),
       ("List All Branches", "git branch -a"),
       ("Create and Switch", "git switch -c {arg}"),
       ("Switch Branch", "git switch {arg}"),
       ("Create from Current", "git checkout -b {arg}"),
       ("Merge Branch", "git merge {arg}"),
       ("Rebase onto", "git rebase {arg}"),
       ("Rebase Continue", "git rebase --continue"),
       ("Rebase Abort", "git rebase --abort"),
       ("Delete Branch", "git branch -d {arg}"),
       ("Force Delete Branch", "git branch -D {arg}")),
    _g("History and Inspection",
       ("Log", "git log"),
       ("Log Graph", "git log --oneline --graph --decorate --all"),
       ("Log Patch", "git log -p {arg}"),
       ("Show Commit", "git show {arg}"),
       ("Blame File", "git blame {arg}"),
       ("Shortlog", "git shortlog -s"),
       ("Reflog", "git reflog"),
       ("Describe Tags", "git describe --tags"),
       ("List Tags", "git tag"),
       ("Annotated Tag", "git tag -a v1.0 -m \"{arg}\""),
       ("Push Tags", "git push --tags")),
    _g("Undo and Recovery",
       ("Unstage Everything", "git restore --staged ."),
       ("Reset Soft", "git reset --soft HEAD~1"),
       ("Reset Mixed", "git reset --mixed HEAD~1"),
       ("Reset Hard (DANGER)", "git reset --hard HEAD~1"),
       ("Revert Commit", "git revert {arg}"),
       ("Cherry Pick", "git cherry-pick {arg}"),
       ("Stash", "git stash"),
       ("Stash with Message", "git stash push -m \"{arg}\""),
       ("Stash List", "git stash list"),
       ("Stash Pop", "git stash pop"),
       ("Stash Drop", "git stash drop"),
       ("Clean Preview", "git clean -n"),
       ("Clean Files (DANGER)", "git clean -fd")),
    _g("Advanced",
       ("Bisect Start", "git bisect start"),
       ("Bisect Bad", "git bisect bad"),
       ("Bisect Good", "git bisect good {arg}"),
       ("Bisect Reset", "git bisect reset"),
       ("Add Worktree", "git worktree add {arg}"),
       ("List Worktrees", "git worktree list"),
       ("Garbage Collect", "git gc --prune=now"),
       ("Check Integrity", "git fsck"),
       ("Compare Branches", "git cherry -v main"),
       ("Log Merge Commits", "git log --merges --oneline")),
]

GITHUB_CLI_GROUPS = [
    _g("Authentication",
       ("Login", "gh auth login"),
       ("Status", "gh auth status"),
       ("Logout", "gh auth logout"),
       ("Refresh Token Scopes", "gh auth refresh -s repo,workflow")),
    _g("Repositories",
       ("View Current", "gh repo view"),
       ("Clone", "gh repo clone {arg}"),
       ("Create (Private, Push)", "gh repo create {arg} --private --push"),
       ("List Mine", "gh repo list"),
       ("Open in Browser", "gh browse")),
    _g("Pull Requests",
       ("Create (from branch)", "gh pr create --fill"),
       ("List Open", "gh pr list"),
       ("List All", "gh pr list --state all"),
       ("View", "gh pr view {arg}"),
       ("Diff", "gh pr diff {arg}"),
       ("Checkout", "gh pr checkout {arg}"),
       ("Merge (Squash)", "gh pr merge {arg} --squash"),
       ("Merge (Rebase + Delete)", "gh pr merge {arg} --rebase --delete-branch")),
    _g("Issues",
       ("List Open", "gh issue list"),
       ("Create", "gh issue create --title \"{arg}\""),
       ("View", "gh issue view {arg}"),
       ("Close", "gh issue close {arg}")),
    _g("Actions and Releases",
       ("Workflow List", "gh workflow list"),
       ("Run Workflow", "gh workflow run {arg}"),
       ("Run List", "gh run list --limit 10"),
       ("Run View", "gh run view {arg}"),
       ("Re-run Failed", "gh run rerun {arg} --failed"),
       ("Cancel Run", "gh run cancel {arg}"),
       ("Create Release", "gh release create v1.0 --generate-notes"),
       ("Secrets List", "gh secret list")),
]

# --------------------------------------------------------------------------
# CI/CD
# --------------------------------------------------------------------------

CICD_GROUPS = [
    _g("GitHub Actions",
       ("List Workflows", "gh workflow list"),
       ("Run Workflow", "gh workflow run {arg}"),
       ("Recent Runs", "gh run list --limit 15"),
       ("View Run Logs", "gh run view {arg} --log-failed"),
       ("Re-run Failed", "gh run rerun {arg} --failed"),
       ("Cancel Run", "gh run cancel {arg}"),
       ("List Secrets", "gh secret list"),
       ("Set Secret", "gh secret set {arg}")),
    _g("Local Runner (act)",
       ("List Jobs", "act -l"),
       ("Run All Jobs", "act"),
       ("Run One Job", "act -j {arg}"),
       ("Run on Re-run Event", "act -r"),
       ("List Available Images", "act -l -P ubuntu-latest=catthehacker/ubuntu:act-latest")),
    _g("Build and Publish",
       ("Docker Build", "docker build -t {arg} ."),
       ("Docker Build (no cache)", "docker build --no-cache -t {arg} ."),
       ("Docker Push", "docker push {arg}"),
       ("List Images", "docker images"),
       ("Compose Up", "docker compose up -d"),
       ("Compose Down", "docker compose down")),
    _g("Deploy to Cluster",
       ("Apply Manifests", "kubectl apply -f {arg}"),
       ("Rollout Status", "kubectl rollout status deployment/{arg} --timeout=120s"),
       ("Rollout Restart", "kubectl rollout restart deployment/{arg}"),
       ("Rollout Undo", "kubectl rollout undo deployment/{arg}"),
       ("Rollout History", "kubectl rollout history deployment/{arg}"),
       ("Deployment Status", "kubectl get deployments -o wide"),
       ("Pod Logs", "kubectl logs -f deployment/{arg} --tail=100")),
]

# --------------------------------------------------------------------------
# Jenkins
# --------------------------------------------------------------------------

JENKINS_GROUPS = [
    _g("Container Lifecycle",
       ("Start Jenkins", "docker run -d --name jenkins -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk17"),
       ("Container Status", "docker ps --filter name=jenkins"),
       ("Follow Logs", "docker logs -f jenkins"),
       ("Last 200 Log Lines", "docker logs --tail 200 jenkins"),
       ("Restart", "docker restart jenkins"),
       ("Stop", "docker stop jenkins"),
       ("Remove Container", "docker rm jenkins"),
       ("Remove Volume (DELETES JOBS)", "docker volume rm jenkins_home")),
    _g("Access and Setup",
       ("Initial Admin Password", "docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword"),
       ("Shell into Container", "docker exec -it jenkins bash"),
       ("Jenkins Version", "docker exec jenkins java -jar /usr/share/jenkins/jenkins.war --version"),
       ("API Info (JSON)", "curl -s http://localhost:8080/api/json"),
       ("Computer List", "curl -s http://localhost:8080/computer/api/json?tree=computer[displayName,offline]")),
    _g("Image Management",
       ("Pull Latest LTS", "docker pull jenkins/jenkins:lts-jdk17"),
       ("List Jenkins Images", "docker images jenkins"),
       ("Remove Old Image", "docker image prune -f"),
       ("Inspect Container", "docker inspect jenkins")),
]

# --------------------------------------------------------------------------
# Terraform
# --------------------------------------------------------------------------

TERRAFORM_GROUPS = [
    _g("Core Workflow",
       ("Init", "terraform init"),
       ("Init (Upgrade)", "terraform init -upgrade"),
       ("Validate", "terraform validate"),
       ("Plan", "terraform plan"),
       ("Plan to File", "terraform plan -out=tfplan"),
       ("Apply Saved Plan", "terraform apply tfplan"),
       ("Apply (Auto Approve)", "terraform apply -auto-approve"),
       ("Apply (Full Review)", "terraform apply"),
       ("Destroy (Review First)", "terraform destroy"),
       ("Destroy (Auto Approve)", "terraform destroy -auto-approve")),
    _g("Formatting and Inspection",
       ("Format", "terraform fmt"),
       ("Format Recursive", "terraform fmt -recursive"),
       ("Format Check", "terraform fmt -check"),
       ("Show Plan File", "terraform show"),
       ("Show JSON Plan", "terraform show -json tfplan"),
       ("Providers", "terraform providers"),
       ("Version", "terraform version"),
       ("Graph", "terraform graph -type=plan")),
    _g("State Management",
       ("State List", "terraform state list"),
       ("State Show", "terraform state show {arg}"),
       ("State Remove", "terraform state rm {arg}"),
       ("Refresh State", "terraform refresh"),
       ("Force Unlock", "terraform force-unlock {arg}"),
       ("Output", "terraform output"),
       ("Output JSON", "terraform output -json"),
       ("Back Up State", "terraform state pull > terraform.tfstate.backup")),
    _g("Workspaces",
       ("List Workspaces", "terraform workspace list"),
       ("New Workspace", "terraform workspace new {arg}"),
       ("Select Workspace", "terraform workspace select {arg}"),
       ("Delete Workspace", "terraform workspace delete {arg}")),
    _g("Advanced",
       ("Import Resource", "terraform import {arg}"),
       ("Target Resource", "terraform apply -target={arg}"),
       ("Taint Resource", "terraform taint {arg}"),
       ("Untaint Resource", "terraform untaint {arg}"),
       ("Console Expression", "terraform console"),
       ("List Functions", "terraform metadata functions -json")),
]

# --------------------------------------------------------------------------
# Ansible
# --------------------------------------------------------------------------

ANSIBLE_GROUPS = [
    _g("Quick Checks",
       ("Ping All", "ansible all -m ping"),
       ("Ping Group", "ansible webservers -m ping"),
       ("Version", "ansible --version"),
       ("Ad-hoc Shell", "ansible all -m shell -a \"{arg}\""),
       ("Ad-hoc Command", "ansible all -m command -a \"{arg}\""),
       ("Run as Root", "ansible all -b -m {arg}")),
    _g("Playbooks",
       ("Run Playbook", "ansible-playbook {arg}"),
       ("Check Mode", "ansible-playbook {arg} --check --diff"),
       ("Syntax Check", "ansible-playbook {arg} --syntax-check"),
       ("Limit Hosts", "ansible-playbook {arg} --limit webservers"),
       ("Start at Task", "ansible-playbook {arg} --start-at-task \"{arg}\""),
       ("Run by Tag", "ansible-playbook {arg} --tags deploy"),
       ("List Tags", "ansible-playbook {arg} --list-tags"),
       ("Step by Step", "ansible-playbook {arg} --step"),
       ("Verbose", "ansible-playbook {arg} -vvv")),
    _g("Inventory",
       ("Inventory Graph", "ansible-inventory --graph"),
       ("Inventory List", "ansible-inventory --list"),
       ("Host Details", "ansible-inventory --host web1"),
       ("Custom Inventory File", "ansible -i {arg} all -m ping"),
       ("Gather Facts", "ansible all -m setup"),
       ("Config Dump", "ansible-config dump"),
       ("Config List", "ansible-config list")),
    _g("Vault and Collections",
       ("Create Vault", "ansible-vault create {arg}"),
       ("Edit Vault", "ansible-vault edit {arg}"),
       ("View Vault", "ansible-vault view {arg}"),
       ("Encrypt File", "ansible-vault encrypt {arg}"),
       ("Decrypt File", "ansible-vault decrypt {arg}"),
       ("Install Collection", "ansible-galaxy collection install {arg}"),
       ("List Collections", "ansible-galaxy collection list"),
       ("Init Role", "ansible-galaxy role init {arg}"),
       ("Docs List", "ansible-doc -l")),
]
# --------------------------------------------------------------------------
# Security testing
# --------------------------------------------------------------------------

SECURITY_GROUPS = [
    _g("Reconnaissance",
       ("Quick Port Scan", "nmap -sV {arg}"),
       ("Full Service Scan", "nmap -sV -sC -A -p- {arg}"),
       ("Web App Scan", "nikto -h {arg}"),
       ("Find Web Files", "feroxbuster -u {arg} -w"),
       ("Fingerprint the Stack", "whatweb {arg}"),
       ("DNS Records", "dig {arg}")),
    _g("Application Scanning",
       ("OWASP ZAP Baseline", "zap-baseline.py -t {arg}"),
       ("OWASP ZAP Active Scan", "zap.sh -cmd \"quickurl.cmd -quickurl {arg}\""),
       ("Nuclei Templates", "nuclei -l {arg}"),
       ("SQL Injection Probe", "sqlmap -u \"{arg}\" --batch"),
       ("OpenSSL / TLS Check", "testssl.sh {arg}")),
    _g("Static Analysis (SAST)",
       ("Python Bandit", "bandit -r {arg}"),
       ("Semgrep Rules", "semgrep --config auto {arg}"),
       ("Brakeman for Rails", "brakeman -q -w {arg}"),
       ("Secrets in Files", "gitleaks detect --source {arg}")),
    _g("Dependency Scanning (SCA)",
       ("Python pip-audit", "pip-audit -r {arg}"),
       ("Node npm audit", "npm audit --prefix {arg}"),
       ("OSV Vulnerabilities", "osv-scanner scan source -r {arg}"),
       ("Trivy Image Scan", "trivy image {arg}"),
       ("Trivy Filesystem", "trivy fs {arg}")),
    _g("Container and Host",
       ("Docker Image CVEs", "trivy image --severity HIGH,CRITICAL {arg}"),
       ("Cluster Role Review", "kubectl get clusterroles,roles -A"),
       ("Running Pods and Security Context", "kubectl get pods -A -o wide"),
       ("Network Policies", "kubectl get networkpolicies -A")),
    _g("CI/CD Security Gates",
       ("Run Every SAST Check", "bandit -r src && semgrep --config auto && gitleaks detect"),
       ("Fail Build on High CVEs", "trivy image --exit-code 1 --severity HIGH,CRITICAL {arg}"),
       ("Confirm CI Signing Key", "gh secret list"),
       ("Show Recent Workflow Runs", "gh run list --limit {arg}")),
]

# --------------------------------------------------------------------------
# Firewalls
# --------------------------------------------------------------------------

FIREWALL_GROUPS = [
    _g("ufw (Ubuntu)",
       ("Show Status", "ufw status verbose"),
       ("Enable", "sudo ufw enable"),
       ("Default Deny Incoming", "sudo ufw default deny incoming"),
       ("Allow SSH", "sudo ufw allow 22/tcp"),
       ("Allow HTTP and HTTPS", "sudo ufw allow 80/tcp && sudo ufw allow 443/tcp"),
       ("Allow From One IP", "sudo ufw allow from {arg}"),
       ("Delete a Rule", "sudo ufw delete allow {arg}")),
    _g("firewalld (RHEL/CentOS)",
       ("Show Active Zone", "sudo firewall-cmd --list-all"),
       ("Show All Zones", "sudo firewall-cmd --list-all-zones"),
       ("Allow a Service", "sudo firewall-cmd --permanent --add-service=http && sudo firewall-cmd --reload"),
       ("Add a Rich Rule", "sudo firewall-cmd --permanent --add-rich-rule='rule family=ipv4 source address={arg} port port=443 protocol=tcp accept'"),
       ("Inspect the Public Zone", "sudo firewall-cmd --zone=public --list-all")),
    _g("nftables",
       ("Show Ruleset", "sudo nft list ruleset"),
       ("Show One Table", "sudo nft list table inet {arg}"),
       ("Show Ruleset as JSON", "sudo nft -j list ruleset"),
       ("Flush the Ruleset", "sudo nft flush ruleset")),
    _g("iptables (legacy)",
       ("Show Filter Rules", "sudo iptables -L -n -v"),
       ("Show Rules as Specs", "sudo iptables -S"),
       ("Allow Established Traffic", "sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT"),
       ("Drop Everything Else", "sudo iptables -A INPUT -j DROP")),
    _g("Windows Defender Firewall",
       ("Show Profiles", "netsh advfirewall show allprofiles"),
       ("Show Firewall Rules", "netsh advfirewall firewall show rule name=all"),
       ("Enable All Profiles", "netsh advfirewall set allprofiles state on"),
       ("Allow Inbound a Port", "netsh advfirewall firewall add rule name=\"Allow {arg}\" dir=in action=allow protocol=TCP localport={arg}"),
       ("Block Outbound for a Program", "netsh advfirewall firewall add rule name=\"Block {arg}\" dir=out action=block program={arg}")),
    _g("Read the Logs",
       ("UFW Log File", "sudo tail -n 50 /var/log/ufw.log"),
       ("Kernel Firewall Messages", "sudo dmesg | findstr /i firewall"),
       ("Test a Port From Windows", "Test-NetConnection -ComputerName {arg} -Port 443")),
]

# --------------------------------------------------------------------------
# Diagrams
# --------------------------------------------------------------------------

DIAGRAM_GROUPS = [
    _g("PlantUML",
       ("Render a File to PNG", "plantuml -tpng {arg}"),
       ("Render to SVG", "plantuml -tsvg {arg}"),
       ("Check a File Parses", "plantuml -checkonly {arg}"),
       ("Serve a Live Editor", "plantuml -server")),
    _g("Graphviz",
       ("Render a DOT File", "dot -Tpng {arg} -o diagram.png"),
       ("Render to SVG", "dot -Tsvg {arg} -o diagram.svg"),
       ("Render to PDF", "dot -Tpdf {arg} -o diagram.pdf"),
       ("Check a DOT File", "dot -Tcanon {arg} > NUL")),
    _g("Mermaid",
       ("Render to SVG", "mmdc -i {arg} -o diagram.svg"),
       ("Render to PNG", "mmdc -i {arg} -o diagram.png"),
       ("Render Every File in a Folder", "mmdc -i docs/ -o out/")),
    _g("Database Schema Diagrams",
       ("Render a dbdiagram.io File", "dbml-renderer {arg}"),
       ("Generate SQL from dbdiagram", "dbml2sql {arg}"),
       ("Export Schema from Postgres", "pg_dump -s -d {arg} > schema.sql"),
       ("Export Schema from MySQL", "mysqldump --no-data {arg} > schema.sql")),
    _g("Architecture as Code",
       ("Validate PlantUML Source", "plantuml -checkonly {arg}"),
       ("Count Lines of a Diagram File", "findstr /n /r \"^\" {arg}")),
]

# --------------------------------------------------------------------------
# Database administration
#
# Distinct from DATABASE_COMMANDS above, which deploys each engine on
# Kubernetes. These drive a database you already have a client for.
# --------------------------------------------------------------------------

DATABASE_ADMIN_GROUPS = [
    _g("PostgreSQL",
       ("List Databases", "psql -U postgres -c '\\l'"),
       ("List Tables", "psql -U postgres -d {arg} -c '\\dt'"),
       ("Describe a Table", "psql -U postgres -d {arg} -c '\\d+'"),
       ("Show Indexes", "psql -U postgres -d {arg} -c '\\di'"),
       ("Database Size", "psql -U postgres -c '\\l+'"),
       ("Vacuum and Analyse", "psql -U postgres -c 'VACUUM ANALYSE;'"),
       ("Dump Schema Only", "pg_dump -s -d {arg} > schema.sql"),
       ("Dump Full Database", "pg_dump -d {arg} > dump.sql")),
    _g("MySQL",
       ("List Databases", "mysql -u root -p -e 'SHOW DATABASES;'"),
       ("List Tables", "mysql -u root -p -D {arg} -e 'SHOW TABLES;'"),
       ("Describe a Table", "mysql -u root -p -D {arg} -e 'DESCRIBE users;'"),
       ("Show Indexes", "mysql -u root -p -D {arg} -e 'SHOW INDEX FROM users;'"),
       ("Explain a Query", "mysql -u root -p -D {arg} -e 'EXPLAIN SELECT * FROM users WHERE email=\"a@b.c\";'"),
       ("Dump Schema Only", "mysqldump --no-data {arg} > schema.sql"),
       ("Dump Full Database", "mysqldump {arg} > dump.sql")),
    _g("MongoDB",
       ("Show Databases", "mongosh --eval 'db.adminCommand({listDatabases:1})'"),
       ("List Collections", "mongosh {arg} --eval 'db.getCollectionNames()'"),
       ("Sample Documents", "mongosh {arg} --eval 'db.orders.find().limit(5)'"),
       ("Explain a Query", "mongosh {arg} --eval 'db.orders.find({status:\"paid\"}).explain(\"executionStats\")'"),
       ("Create an Index", "mongosh {arg} --eval 'db.orders.createIndex({customerId:1, createdAt:-1})'"),
       ("List Indexes", "mongosh {arg} --eval 'db.orders.getIndexes()'")),
    _g("Schema Design and Normalisation",
       ("Find Duplicate Values", "psql -U postgres -d {arg} -c 'SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;'"),
       ("Find Rows With Nulls", "psql -U postgres -d {arg} -c 'SELECT COUNT(*) FROM orders WHERE customer_id IS NULL;'"),
       ("Show Foreign Keys", "psql -U postgres -d {arg} -c '\\d orders'"),
       ("Check Relationship Cardinality", "psql -U postgres -d {arg} -c 'SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id ORDER BY 2 DESC LIMIT 10;'"),
       ("Show Row Counts", "psql -U postgres -d {arg} -c 'SELECT relname, n_live_tup FROM pg_stat_user_tables ORDER BY n_live_tup DESC;'"),
       ("Find Unused Indexes", "psql -U postgres -d {arg} -c 'SELECT relname, indexrelname FROM pg_stat_user_indexes WHERE idx_scan = 0;'")),
]

# --------------------------------------------------------------------------
# Windows legacy diagnosis commands
#
# The classic set a Windows admin reaches for when a machine misbehaves:
# wmic, ipconfig, netstat, nbtstat, wevtutil, sfc, DISM, msconfig and the
# .msc consoles. Grouped the way the Diagnostics chapter presents them, so
# the panel, the book and the phone app all tell the same story.
# --------------------------------------------------------------------------

WINDOWS_DIAG_GROUPS = [
    _g("System Information",
       ("System Summary", "systeminfo"),
       ("Quick OS Summary", "systeminfo | findstr /C:\"OS Name\" /C:\"Boot Time\" /C:\"Total Physical Memory\""),
       ("System Info GUI", "msinfo32"),
       ("Windows Version", "winver"),
       ("Last Boot Time", "wmic os get lastbootuptime /value"),
       ("CPU Model", "wmic cpu get name"),
       ("BIOS Version", "wmic bios get smbiosbiosversion"),
       ("Machine Model", "wmic csproduct get name,identifyingnumber")),
    _g("Memory Diagnostics",
       ("Memory Sticks", "wmic memorychip get devicelocator,capacity,speed,status"),
       ("Memory Modules Full", "wmic memorychip list full"),
       ("Free and Total RAM", "wmic os get FreePhysicalMemory,TotalVisibleMemorySize /value"),
       ("Memory Test (reboots)", "mdsched.exe"),
       ("Resource Monitor", "resmon")),
    _g("Disk and Storage",
       ("Logical Disks", "wmic logicaldisk get caption,freespace,size,volumename"),
       ("Physical Disks", "wmic diskdrive get model,status,size"),
       ("Disk Health", "wmic diskdrive get status"),
       ("Volume Free Space", "fsutil volume diskfree c:"),
       ("Check Disk (read-only)", "chkdsk {arg}"),
       ("Check Disk (repair)", "chkdsk {arg} /f"),
       ("Defragment Analysis", "defrag {arg} /A /U /V"),
       ("Physical Disk List", "diskpart list disk")),
    _g("Network Diagnostics",
       ("Full IP Config", "ipconfig /all"),
       ("Flush DNS Cache", "ipconfig /flushdns"),
       ("Show DNS Cache", "ipconfig /displaydns"),
       ("Release DHCP", "ipconfig /release"),
       ("Renew DHCP", "ipconfig /renew"),
       ("Ping (continuous)", "ping -t {arg}"),
       ("Ping 4 Packets", "ping -n 4 {arg}"),
       ("Trace Route", "tracert -d {arg}"),
       ("Path Ping (latency)", "pathping {arg}"),
       ("ARP Table", "arp -a"),
       ("Routing Table", "route print"),
       ("NetBIOS Names", "nbtstat -n"),
       ("Remote NetBIOS", "nbtstat -A {arg}"),
       ("MAC Addresses", "getmac /all"),
       ("DNS Lookup", "nslookup {arg}"),
       ("Active Connections", "netstat -ano"),
       ("Listening Ports", "netstat -ano | findstr LISTENING"),
       ("Connection Statistics", "netstat -s"),
       ("Remote Shares", "net view"),
       ("Network Adapters", "wmic nic get name,speed")),
    _g("Wireless (netsh)",
       ("Current Connection", "netsh wlan show interfaces"),
       ("Visible Networks", "netsh wlan show networks mode=bssid"),
       ("Driver Info", "netsh wlan show drivers"),
       ("Security Mode", "netsh wlan show security"),
       ("Saved Profiles", "netsh wlan show profile")),
    _g("Processes and Services",
       ("Process List", "tasklist"),
       ("Processes With Services", "tasklist /svc"),
       ("Process Modules", "tasklist /m"),
       ("Kill By Image Name", "taskkill /F /IM {arg}"),
       ("Kill By PID", "taskkill /F /PID {arg}"),
       ("Service Details", "sc query {arg}"),
       ("Service Config", "sc qc {arg}"),
       ("All Service States", "sc queryex type=service state=all"),
       ("Start Service", "net start {arg}"),
       ("Stop Service", "net stop {arg}"),
       ("Services Console", "services.msc")),
    _g("Event Logs and Reliability",
       ("Event Viewer", "eventvwr"),
       ("List Event Logs", "wevtutil el"),
       ("Query System Log", "wevtutil qe System /c:20 /rd:true /f:text"),
       ("Query Application Log", "wevtutil qe Application /c:20 /rd:true /f:text"),
       ("Query Crash Entries", "wevtutil qe Application /c:10 /rd:true /f:text /q:*[System[(Level=1 or Level=2)]]"),
       ("Reliability Monitor", "perfmon /rel"),
       ("Performance Monitor", "perfmon"),
       ("DirectX Diagnostics", "dxdiag")),
    _g("System Repair",
       ("System File Checker", "sfc /scannow"),
       ("DISM Health Check", "DISM /Online /Cleanup-Image /CheckHealth"),
       ("DISM Restore Health", "DISM /Online /Cleanup-Image /RestoreHealth"),
       ("DISM Component Cleanup", "DISM /Online /Cleanup-Image /StartComponentCleanup"),
       ("Check Disk (repair C:)", "chkdsk C: /f /r")),
    _g("Boot and Startup",
       ("Boot Configuration", "bcdedit /enum"),
       ("Default Boot Entry", "bcdedit /enum {current}"),
       ("Safe Mode Entry", "bcdedit /enum {safeboot}"),
       ("System Configuration", "msconfig"),
       ("Refresh Group Policy", "gpupdate /force"),
       ("Resultant Group Policy", "gpresult /r")),
    _g("Hardware and Devices",
       ("Device Manager", "devmgmt.msc"),
       ("Disk Management", "diskmgmt.msc"),
       ("Computer Management", "compmgmt.msc"),
       ("Connected Devices", "wmic path win32_pnpentity get name,status"),
       ("Display Adapter", "wmic path win32_videocontroller get name,driverversion"),
       ("Attached Printers", "wmic printer list brief")),
]

# Argument placeholders shown for each group type.
ARG_PLACEHOLDERS = {
    "git": "branch, file, commit, URL...",
    "gh": "PR/issue number, repo, workflow...",
    "cicd": "workflow, job, image tag, path...",
    "terraform": "resource address, workspace...",
    "ansible": "playbook.yml, group, module...",
    "security": "target host, URL, path or scan scope...",
    "firewall": "port, service name, source IP, rule name...",
    "diagram": "file to render, e.g. diagram.puml...",
    "database": "database name, table, or client options...",
    "docker": "container, image, network or volume name...",
    "windows": "drive letter, service name, host or IP...",
}