name: Build Electron Desktop App

on:
  push:
    branches:
      - main
    paths:
      - 'DockKubeDesktop/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install and Build Desktop
        working-directory: ./DockKubeDesktop
        run: |
          # --- PYTHON BUILD STEPS ---
          pip install pyinstaller
          
          # Replace 'main.py' with the actual name of your Python file!
          pyinstaller --onefile main.py
          
          # --- ELECTRON BUILD STEPS ---
          npm install
          npm run build
